### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by haesleinhuepf** [m-albert/Virtual-I2K-2024-multiview-stitcher#1]
Hi Marvin @m-albert ,

nice repository! Great that you are sharing it open source! I was just wondering under which conditions one could reuse the materials provided here, e.g. for teaching courses and therefore resharing your materials. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blog post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by m-albert** [comment]
Hi Robert @haesleinhuepf ,

thanks a lot for your interest and the reminder to add a license.

I just added a license file and really like your summary issue https://github.com/NFDI4BIOIMAGE/licensing/issues/1 :)

Cheers,
Marvin
